// Single source of truth for the platform's India state → city taxonomy.
// Replaces the old flat ~7-city "metro only" lists that used to be hardcoded
// separately (and inconsistently) in three different frontend pages. See
// frontend/lib/locations.ts for the mirror.
//
// Selection is two-step: pick a state/UT, then pick one or more cities within
// it. Lists go well beyond the district-headquarters level into significant
// sub-divisional towns and municipalities per client feedback that cities
// like Kandi, Tamluk and Kanthi (in West Bengal) were missing even though
// they're well-known towns — so coverage is now as deep as we can reliably
// curate by hand, not just the biggest city per district. It is still not
// literally every census town in India (there are several thousand of
// those); if a specific town is still missing, add it here and mirror the
// same addition in frontend/lib/locations.ts.
// City values already stored on old records (all metro names) are preserved
// verbatim inside their correct state so legacy data keeps matching.

const LOCATIONS = [
  { state: 'Andhra Pradesh', cities: ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Nellore', 'Kurnool', 'Kakinada', 'Rajahmundry', 'Tirupati', 'Kadapa', 'Anantapur', 'Eluru', 'Ongole', 'Chittoor', 'Srikakulam', 'Vizianagaram', 'Machilipatnam', 'Tenali', 'Proddatur', 'Hindupur', 'Bhimavaram', 'Madanapalle', 'Guntakal', 'Dharmavaram', 'Gudivada', 'Narasaraopet', 'Tadipatri', 'Tadepalligudem', 'Chilakaluripet', 'Yemmiganur', 'Kadiri', 'Chirala', 'Adoni', 'Nandyal', 'Palasa', 'Amalapuram', 'Bapatla', 'Kavali', 'Ponnur', 'Vinukonda', 'Nuzvid', 'Markapur', 'Rajam', 'Narasapuram', 'Palakollu', 'Tanuku', 'Bobbili', 'Naidupeta', 'Gudur', 'Repalle', 'Macherla', 'Jaggampeta', 'Rayachoti', 'Punganur', 'Pithapuram', 'Ramachandrapuram', 'Peddapuram', 'Tuni', 'Salur', 'Parvathipuram', 'Nagari', 'Puttaparthi'] },
  { state: 'Arunachal Pradesh', cities: ['Itanagar', 'Naharlagun', 'Pasighat', 'Tawang', 'Ziro', 'Bomdila', 'Along (Aalo)', 'Tezu', 'Changlang', 'Khonsa', 'Roing', 'Anini', 'Daporijo', 'Yingkiong', 'Seppa', 'Namsai', 'Yupia', 'Basar', 'Koloriang'] },
  { state: 'Assam', cities: ['Guwahati', 'Silchar', 'Dibrugarh', 'Jorhat', 'Nagaon', 'Tinsukia', 'Tezpur', 'Karimganj', 'Sivasagar', 'Bongaigaon', 'Diphu', 'North Lakhimpur', 'Dhubri', 'Goalpara', 'Barpeta', 'Nalbari', 'Mangaldoi', 'Golaghat', 'Hailakandi', 'Morigaon', 'Kokrajhar', 'Hojai', 'Sonari', 'Digboi', 'Margherita', 'Rangia', 'Haflong', 'Lumding', 'Dhekiajuli', 'Biswanath Chariali', 'Bilasipara', 'Abhayapuri', 'Sapatgram', 'Silapathar', 'Mankachar', 'Nazira', 'Amguri', 'Titabor', 'Doom Dooma', 'Duliajan', 'Namrup', 'Mariani', 'Dhemaji', 'Barpeta Road', 'Rangapara'] },
  { state: 'Bihar', cities: ['Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Darbhanga', 'Purnia', 'Arrah', 'Begusarai', 'Katihar', 'Munger', 'Chapra', 'Bihar Sharif', 'Motihari', 'Bettiah', 'Saharsa', 'Sasaram', 'Hajipur', 'Dehri', 'Siwan', 'Buxar', 'Kishanganj', 'Jamalpur', 'Jehanabad', 'Aurangabad', 'Gopalganj', 'Nawada', 'Bagaha', 'Madhubani', 'Samastipur', 'Sitamarhi', 'Supaul', 'Araria', 'Khagaria', 'Lakhisarai', 'Sheohar', 'Sheikhpura', 'Banka', 'Jamui', 'Madhepura', 'Danapur', 'Barh', 'Bikramganj', 'Dumraon', 'Rajgir', 'Bodh Gaya', 'Silao', 'Barbigha', 'Sherghati', 'Warisaliganj', 'Rafiganj', 'Mokameh', 'Bakhtiyarpur', 'Fatuha', 'Naugachhia', 'Bihpur', 'Forbesganj', 'Raxaul', 'Narkatiaganj', 'Areraj'] },
  { state: 'Chhattisgarh', cities: ['Raipur', 'Bhilai', 'Bilaspur', 'Korba', 'Durg', 'Rajnandgaon', 'Jagdalpur', 'Raigarh', 'Ambikapur', 'Dhamtari', 'Mahasamund', 'Kanker', 'Kawardha', 'Champa', 'Naila Janjgir', 'Chirmiri', 'Bhatapara', 'Dongargarh', 'Baloda Bazar', 'Kondagaon', 'Tilda Newra', 'Bhilai Charoda', 'Pathalgaon', 'Sakti', 'Jashpur', 'Kunkuri', 'Gariaband', 'Balod', 'Bemetara', 'Baikunthpur', 'Manendragarh', 'Narayanpur', 'Bijapur (Chhattisgarh)', 'Sukma', 'Dantewada', 'Katghora'] },
  { state: 'Goa', cities: ['Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda', 'Bicholim', 'Curchorem', 'Sanguem', 'Canacona', 'Pernem', 'Cuncolim', 'Valpoi', 'Quepem', 'Sanquelim', 'Aldona'] },
  { state: 'Gujarat', cities: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar', 'Jamnagar', 'Gandhinagar', 'Junagadh', 'Anand', 'Nadiad', 'Mehsana', 'Bharuch', 'Vapi', 'Morbi', 'Navsari', 'Veraval', 'Porbandar', 'Godhra', 'Bhuj', 'Anjar', 'Gandhidham', 'Patan', 'Palanpur', 'Botad', 'Amreli', 'Surendranagar', 'Valsad', 'Deesa', 'Jetpur', 'Wankaner', 'Gondal', 'Dahod', 'Vyara', 'Ankleshwar', 'Kalol', 'Himatnagar', 'Modasa', 'Bardoli', 'Amroli', 'Petlad', 'Kadi', 'Visnagar', 'Unjha', 'Sidhpur', 'Dhoraji', 'Upleta', 'Rajpipla', 'Mandvi (Kutch)', 'Mundra', 'Naliya', 'Kapadvanj', 'Vadnagar', 'Vallabh Vidyanagar', 'Chhota Udaipur', 'Dhrangadhra', 'Jasdan', 'Talaja', 'Mahuva', 'Una (Gujarat)', 'Keshod', 'Manavadar', 'Rajula', 'Sihor', 'Songadh'] },
  { state: 'Haryana', cities: ['Gurugram', 'Faridabad', 'Panipat', 'Ambala', 'Yamunanagar', 'Rohtak', 'Hisar', 'Karnal', 'Sonipat', 'Panchkula', 'Bhiwani', 'Sirsa', 'Kaithal', 'Rewari', 'Jind', 'Kurukshetra', 'Palwal', 'Jhajjar', 'Fatehabad', 'Mahendragarh', 'Narnaul', 'Pehowa', 'Tohana', 'Thanesar', 'Bahadurgarh', 'Hansi', 'Narwana', 'Charkhi Dadri', 'Ratia', 'Ellenabad', 'Ganaur', 'Samalkha', 'Gohana', 'Safidon', 'Assandh', 'Ladwa', 'Shahabad Markanda', 'Radaur', 'Pinjore', 'Kalka', 'Taraori', 'Uchana'] },
  { state: 'Himachal Pradesh', cities: ['Shimla', 'Manali', 'Dharamshala', 'Solan', 'Mandi', 'Kullu', 'Bilaspur', 'Una', 'Hamirpur', 'Chamba', 'Nahan', 'Kangra', 'Nurpur', 'Palampur', 'Baddi', 'Paonta Sahib', 'Sundarnagar', 'Kasauli', 'Rampur', 'Reckong Peo', 'Keylong', 'Jogindernagar', 'Nalagarh', 'Arki', 'Theog', 'Rohru', 'Jubbal', 'Dalhousie', 'Manikaran', 'Sarkaghat', 'Ghumarwin', 'Jawali', 'Indora', 'Amb', 'Barsar'] },
  { state: 'Jharkhand', cities: ['Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Deoghar', 'Hazaribagh', 'Giridih', 'Ramgarh', 'Medininagar (Daltonganj)', 'Phusro', 'Chaibasa', 'Chirkunda', 'Dumka', 'Gumla', 'Godda', 'Sahibganj', 'Pakur', 'Chatra', 'Koderma', 'Lohardaga', 'Simdega', 'Jamtara', 'Khunti', 'Latehar', 'Chakradharpur', 'Jhumri Telaiya', 'Rajmahal', 'Madhupur', 'Sarath', 'Barharwa', 'Barkatha', 'Chandil', 'Ghatshila', 'Musabani', 'Adityapur', 'Mango', 'Bundu', 'Gomoh', 'Nirsa', 'Jhinkpani'] },
  { state: 'Karnataka', cities: ['Bangalore', 'Mysore', 'Hubli', 'Mangalore', 'Belgaum', 'Davanagere', 'Bellary', 'Shimoga', 'Tumkur', 'Udupi', 'Gulbarga', 'Hassan', 'Bijapur', 'Bidar', 'Raichur', 'Hospet', 'Gadag', 'Chitradurga', 'Kolar', 'Mandya', 'Chikmagalur', 'Robertsonpet (KGF)', 'Karwar', 'Bagalkot', 'Ranebennuru', 'Ramanagara', 'Gangavati', 'Yadgir', 'Chikkaballapur', 'Koppal', 'Sirsi', 'Puttur', 'Kundapura', 'Madikeri', 'Sagar', 'Haveri', 'Bhadravati', 'Chamarajanagar', 'Yellapur', 'Sidlaghatta', 'Channapatna', 'Malavalli', 'Nanjangud', 'Gundlupet', 'Arsikere', 'Tiptur', 'Sira', 'Pavagada', 'Chintamani', 'Bagepalli', 'Athani', 'Chikodi', 'Jamkhandi', 'Mudhol', 'Bailhongal', 'Gokak', 'Ron', 'Nargund', 'Shahapur', 'Shorapur', 'Sindhanur', 'Manvi', 'Kushtagi'] },
  { state: 'Kerala', cities: ['Kochi', 'Thiruvananthapuram', 'Kozhikode', 'Thrissur', 'Kollam', 'Kannur', 'Alappuzha', 'Kottayam', 'Palakkad', 'Malappuram', 'Kasaragod', 'Idukki', 'Pathanamthitta', 'Wayanad', 'Thodupuzha', 'Kayamkulam', 'Perinthalmanna', 'Manjeri', 'Ponnani', 'Guruvayur', 'Chalakudy', 'Muvattupuzha', 'Changanassery', 'Nedumangad', 'Attingal', 'Punalur', 'Kanhangad', 'Payyanur', 'Kottarakkara', 'Neyyattinkara', 'Varkala', 'Cherthala', 'Tirur', 'Kondotty', 'Nilambur', 'Vatakara', 'Koyilandy', 'Thalassery', 'Mattannur', 'Taliparamba', 'Ottapalam', 'Shoranur', 'Chittur', 'Pattambi', 'Angamaly', 'Perumbavoor', 'Kothamangalam', 'Aluva', 'North Paravur', 'Tripunithura', 'Kunnamkulam', 'Irinjalakuda', 'Kodungallur', 'Pala', 'Ranni', 'Adoor', 'Pandalam', 'Mavelikkara'] },
  { state: 'Madhya Pradesh', cities: ['Indore', 'Bhopal', 'Jabalpur', 'Gwalior', 'Ujjain', 'Sagar', 'Dewas', 'Satna', 'Ratlam', 'Rewa', 'Murwara (Katni)', 'Singrauli', 'Burhanpur', 'Khandwa', 'Chhindwara', 'Guna', 'Shivpuri', 'Vidisha', 'Chhatarpur', 'Damoh', 'Mandsaur', 'Khargone', 'Neemuch', 'Betul', 'Seoni', 'Sehore', 'Datia', 'Nagda', 'Itarsi', 'Sarni', 'Balaghat', 'Hoshangabad', 'Shahdol', 'Morena', 'Bhind', 'Pithampur', 'Mandla', 'Tikamgarh', 'Panna', 'Ashoknagar', 'Shajapur', 'Mhow', 'Harda', 'Raisen', 'Sidhi', 'Rajgarh', 'Anuppur', 'Umaria', 'Waraseoni', 'Multai', 'Barwani', 'Sendhwa', 'Jaora', 'Narsinghpur'] },
  { state: 'Maharashtra', cities: ['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Aurangabad', 'Thane', 'Solapur', 'Kolhapur', 'Amravati', 'Navi Mumbai', 'Sangli', 'Akola', 'Jalgaon', 'Latur', 'Nanded', 'Kalyan-Dombivli', 'Vasai-Virar', 'Malegaon', 'Dhule', 'Ahmednagar', 'Chandrapur', 'Parbhani', 'Ichalkaranji', 'Jalna', 'Bhiwandi', 'Panvel', 'Satara', 'Beed', 'Yavatmal', 'Achalpur', 'Osmanabad', 'Nandurbar', 'Wardha', 'Udgir', 'Hinganghat', 'Ratnagiri', 'Gondia', 'Baramati', 'Karad', 'Sindhudurg (Oros)', 'Washim', 'Bhandara', 'Vasai', 'Virar', 'Ambernath', 'Badlapur', 'Ulhasnagar', 'Miraj', 'Barshi', 'Pandharpur', 'Shirdi', 'Lonavala', 'Khopoli', 'Alibag', 'Wai', 'Phaltan', 'Malkapur', 'Buldhana', 'Khamgaon', 'Shegaon', 'Chalisgaon', 'Bhusawal', 'Amalner', 'Pusad', 'Deoli', 'Ballarpur', 'Warora', 'Rajura', 'Sillod', 'Vaijapur', 'Georai', 'Ambajogai', 'Manmad', 'Nandgaon', 'Sinnar', 'Igatpuri'] },
  { state: 'Manipur', cities: ['Imphal', 'Thoubal', 'Bishnupur', 'Churachandpur', 'Kakching', 'Senapati', 'Ukhrul', 'Tamenglong', 'Jiribam', 'Moirang', 'Lilong', 'Mayang Imphal'] },
  { state: 'Meghalaya', cities: ['Shillong', 'Tura', 'Jowai', 'Nongstoin', 'Baghmara', 'Williamnagar', 'Nongpoh', 'Resubelpara', 'Mairang', 'Khliehriat'] },
  { state: 'Mizoram', cities: ['Aizawl', 'Lunglei', 'Champhai', 'Serchhip', 'Kolasib', 'Saiha', 'Lawngtlai', 'Mamit', 'Bairabi', 'Zawlnuam'] },
  { state: 'Nagaland', cities: ['Kohima', 'Dimapur', 'Mokokchung', 'Tuensang', 'Wokha', 'Zunheboto', 'Phek', 'Mon', 'Kiphire', 'Peren', 'Chumukedima', 'Pfutsero'] },
  { state: 'Odisha', cities: ['Bhubaneswar', 'Cuttack', 'Rourkela', 'Berhampur', 'Sambalpur', 'Puri', 'Balasore', 'Bhadrak', 'Baripada', 'Jharsuguda', 'Jeypore', 'Bargarh', 'Rayagada', 'Kendrapara', 'Angul', 'Dhenkanal', 'Koraput', 'Paradip', 'Balangir', 'Bhawanipatna', 'Nabarangpur', 'Sundargarh', 'Talcher', 'Konark', 'Phulbani', 'Nayagarh', 'Jajpur', 'Titlagarh', 'Kesinga', 'Bhanjanagar', 'Chatrapur', 'Gopalpur', 'Rajgangpur', 'Kuchinda', 'Athagarh', 'Banki', 'Nimapara', 'Pipili', 'Soro', 'Basta', 'Jaleswar', 'Anandapur', 'Champua', 'Barbil', 'Joda', 'Panposh'] },
  { state: 'Punjab', cities: ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda', 'Mohali', 'Hoshiarpur', 'Pathankot', 'Moga', 'Firozpur', 'Batala', 'Kapurthala', 'Faridkot', 'Muktsar', 'Sangrur', 'Barnala', 'Rajpura', 'Phagwara', 'Abohar', 'Malerkotla', 'Khanna', 'Mansa', 'Gurdaspur', 'Zirakpur', 'Nawanshahr', 'Nabha', 'Tarn Taran', 'Samana', 'Sunam', 'Dhuri', 'Malout', 'Jagraon', 'Raikot', 'Khamano', 'Nakodar', 'Phillaur', 'Shahkot', 'Sultanpur Lodhi', 'Dasuya', 'Mukerian', 'Talwara', 'Anandpur Sahib', 'Rupnagar (Ropar)', 'Kharar', 'Dera Bassi'] },
  { state: 'Rajasthan', cities: ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Bikaner', 'Ajmer', 'Bhilwara', 'Alwar', 'Sikar', 'Bharatpur', 'Pali', 'Sri Ganganagar', 'Sawai Madhopur', 'Churu', 'Jhunjhunu', 'Barmer', 'Tonk', 'Hanumangarh', 'Dausa', 'Nagaur', 'Chittorgarh', 'Banswara', 'Dholpur', 'Beawar', 'Bundi', 'Jaisalmer', 'Karauli', 'Baran', 'Rajsamand', 'Sirohi', 'Jalore', 'Pratapgarh', 'Kishangarh', 'Nasirabad', 'Nathdwara', 'Fatehpur (Sikar)', 'Ratangarh', 'Sujangarh', 'Sardarshahar', 'Nokha', 'Merta City', 'Deshnoke', 'Phalodi', 'Balotra', 'Sheoganj', 'Abu Road', 'Deoli', 'Lachhmangarh', 'Ramganj Mandi', 'Sangod', 'Gangapur City', 'Hindaun', 'Kaman', 'Deeg', 'Nimbahera', 'Bhinmal', 'Sumerpur'] },
  { state: 'Sikkim', cities: ['Gangtok', 'Namchi', 'Gyalshing', 'Mangan', 'Rangpo', 'Jorethang', 'Singtam', 'Ravangla'] },
  { state: 'Tamil Nadu', cities: ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem', 'Tirunelveli', 'Erode', 'Vellore', 'Thoothukudi', 'Thanjavur', 'Dindigul', 'Tiruppur', 'Nagercoil', 'Kanchipuram', 'Karur', 'Cuddalore', 'Kumbakonam', 'Rajapalayam', 'Hosur', 'Nagapattinam', 'Sivakasi', 'Pudukkottai', 'Karaikudi', 'Ambur', 'Namakkal', 'Tiruvannamalai', 'Pollachi', 'Ranipet', 'Krishnagiri', 'Dharmapuri', 'Virudhunagar', 'Theni', 'Vaniyambadi', 'Gudiyatham', 'Neyveli', 'Tiruchengode', 'Rasipuram', 'Attur', 'Mettur', 'Bhavani', 'Gobichettipalayam', 'Sathyamangalam', 'Udumalpet', 'Palani', 'Kodaikanal', 'Mayiladuthurai', 'Chidambaram', 'Sirkazhi', 'Tiruvarur', 'Tirumangalam', 'Aruppukkottai', 'Srivilliputhur', 'Tenkasi', 'Sankarankovil', 'Kovilpatti', 'Villupuram', 'Tindivanam', 'Vandavasi', 'Arakkonam', 'Tiruvallur', 'Ambattur', 'Avadi', 'Chengalpattu', 'Tambaram'] },
  { state: 'Telangana', cities: ['Hyderabad', 'Warangal', 'Nizamabad', 'Karimnagar', 'Khammam', 'Secunderabad', 'Ramagundam', 'Mahbubnagar', 'Nalgonda', 'Adilabad', 'Suryapet', 'Miryalaguda', 'Jagtial', 'Siddipet', 'Mancherial', 'Kothagudem', 'Sangareddy', 'Wanaparthy', 'Vikarabad', 'Bhongir', 'Medak', 'Zaheerabad', 'Jangaon', 'Bhupalpalle', 'Bhadrachalam', 'Kamareddy', 'Nirmal', 'Mandamarri', 'Bellampalli', 'Palwancha', 'Yellandu', 'Metpally', 'Korutla', 'Huzurabad', 'Gadwal', 'Kalwakurthy', 'Achampet', 'Narayanpet', 'Tandur', 'Bodhan', 'Armoor', 'Banswada'] },
  { state: 'Tripura', cities: ['Agartala', 'Udaipur (Tripura)', 'Dharmanagar', 'Kailashahar', 'Belonia', 'Khowai', 'Ambassa', 'Sonamura', 'Kamalpur', 'Teliamura', 'Amarpur', 'Sabroom'] },
  { state: 'Uttar Pradesh', cities: ['Lucknow', 'Kanpur', 'Ghaziabad', 'Agra', 'Varanasi', 'Meerut', 'Prayagraj', 'Noida', 'Bareilly', 'Aligarh', 'Moradabad', 'Gorakhpur', 'Saharanpur', 'Jhansi', 'Mathura', 'Firozabad', 'Muzaffarnagar', 'Rampur', 'Shahjahanpur', 'Faizabad (Ayodhya)', 'Sitapur', 'Etawah', 'Mirzapur', 'Bulandshahr', 'Amroha', 'Hapur', 'Farrukhabad', 'Hardoi', 'Fatehpur', 'Raebareli', 'Orai', 'Sultanpur', 'Basti', 'Unnao', 'Ghazipur', 'Jaunpur', 'Lakhimpur', 'Pilibhit', 'Banda', 'Bijnor', 'Deoria', 'Azamgarh', 'Bahraich', 'Barabanki', 'Etah', 'Mainpuri', 'Auraiya', 'Kannauj', 'Greater Noida', 'Khurja', 'Sikandrabad', 'Modinagar', 'Gajraula', 'Chandausi', 'Sambhal', 'Hathras', 'Kasganj', 'Padrauna', 'Kushinagar', 'Gonda', 'Balrampur', 'Shravasti', 'Siddharthnagar', 'Maharajganj', 'Kaushambi', 'Pratapgarh (UP)', 'Chunar', 'Robertsganj', 'Chandauli', 'Zamania', 'Akbarpur', 'Tanda', 'Mubarakpur', 'Khalilabad', 'Salempur', 'Chhibramau', 'Pilkhuwa', 'Baghpat', 'Shamli', 'Kairana', 'Bhadohi'] },
  { state: 'Uttarakhand', cities: ['Dehradun', 'Haridwar', 'Rishikesh', 'Nainital', 'Haldwani', 'Roorkee', 'Kashipur', 'Rudrapur', 'Ramnagar', 'Almora', 'Pithoragarh', 'Pauri', 'Tehri', 'Chamoli', 'Uttarkashi', 'Bageshwar', 'Champawat', 'Kotdwar', 'Vikasnagar', 'Manglaur', 'Laksar', 'Sitarganj', 'Khatima', 'Jaspur', 'Bazpur', 'Gadarpur', 'Srinagar (Garhwal)', 'Karnaprayag', 'Joshimath', 'Gopeshwar', 'Ranikhet', 'Mussoorie', 'Dwarahat'] },
  { state: 'West Bengal', cities: ['Kolkata', 'Howrah', 'Bally', 'Uluberia', 'Domjur', 'Shibpur', 'Barasat', 'Barrackpore', 'Basirhat', 'Bongaon', 'Habra', 'Ashoknagar-Kalyangarh', 'Bidhannagar (Salt Lake)', 'Naihati', 'Kanchrapara', 'Halisahar', 'Bhatpara', 'Titagarh', 'Khardah', 'Panihati', 'North Barrackpore', 'Gobardanga', 'Taki', 'Baranagar', 'Rajarhat-Gopalpur', 'Madhyamgram', 'New Barrackpore', 'North Dum Dum', 'South Dum Dum', 'Dum Dum', 'Garulia', 'Baruipur', 'Diamond Harbour', 'Canning', 'Jaynagar Mazilpur', 'Budge Budge', 'Pujali', 'Maheshtala', 'Rajpur Sonarpur', 'Falta', 'Kakdwip', 'Joynagar', 'Chandannagar', 'Chinsurah', 'Serampore', 'Rishra', 'Konnagar', 'Uttarpara-Kotrung', 'Baidyabati', 'Champdani', 'Bhadreswar', 'Dankuni', 'Arambagh', 'Tarakeswar', 'Bansberia', 'Jangipara', 'Singur', 'Bardhaman', 'Durgapur', 'Asansol', 'Kulti', 'Raniganj', 'Kalna', 'Katwa', 'Memari', 'Guskara', 'Dainhat', 'Jamuria', 'Barabani', 'Pandaveswar', 'Ondal', 'Suri', 'Bolpur', 'Rampurhat', 'Sainthia', 'Dubrajpur', 'Nalhati', 'Ilambazar', 'Mayureswar', 'English Bazar (Malda)', 'Old Malda', 'Chanchal', 'Harishchandrapur', 'Ratua', 'Baharampur', 'Murshidabad', 'Jangipur', 'Lalgola', 'Dhulian', 'Beldanga', 'Kandi', 'Jiaganj-Azimganj', 'Nabagram', 'Raghunathganj', 'Farakka', 'Sagardighi', 'Raiganj', 'Islampur', 'Kaliyaganj', 'Chopra', 'Karandighi', 'Balurghat', 'Gangarampur', 'Buniadpur', 'Kushmandi', 'Tapan', 'Jalpaiguri', 'Mal', 'Dhupguri', 'Nagrakata', 'Banarhat', 'Alipurduar', 'Falakata', 'Kalchini', 'Cooch Behar', 'Dinhata', 'Mathabhanga', 'Tufanganj', 'Mekhliganj', 'Darjeeling', 'Siliguri', 'Kurseong', 'Mirik', 'Kalimpong', 'Purulia', 'Raghunathpur', 'Jhalda', 'Adra', 'Bankura', 'Bishnupur', 'Sonamukhi', 'Khatra', 'Medinipur', 'Kharagpur', 'Ghatal', 'Chandrakona', 'Tamluk', 'Haldia', 'Contai (Kanthi)', 'Egra', 'Panskura', 'Nandigram', 'Mahishadal', 'Digha', 'Jhargram', 'Krishnanagar', 'Nabadwip', 'Ranaghat', 'Chakdaha', 'Kalyani', 'Santipur', 'Birnagar', 'Tehatta', 'Karimpur', 'Nakashipara'] },
  { state: 'Andaman and Nicobar Islands', cities: ['Port Blair', 'Diglipur', 'Rangat', 'Mayabunder', 'Car Nicobar'] },
  { state: 'Chandigarh', cities: ['Chandigarh'] },
  { state: 'Dadra and Nagar Haveli and Daman and Diu', cities: ['Silvassa', 'Daman', 'Diu'] },
  { state: 'Delhi', cities: ['Delhi', 'New Delhi', 'Dwarka', 'Rohini', 'Karol Bagh', 'Saket', 'Janakpuri', 'Pitampura', 'Vasant Kunj', 'Lajpat Nagar', 'Connaught Place', 'Mayur Vihar', 'Rajouri Garden', 'Shahdara', 'Najafgarh', 'Chandni Chowk', 'Preet Vihar', 'Model Town', 'Paharganj', 'Greater Kailash', 'Hauz Khas', 'Okhla', 'Narela', 'Nangloi'] },
  { state: 'Jammu and Kashmir', cities: ['Srinagar', 'Jammu', 'Anantnag', 'Baramulla', 'Udhampur', 'Sopore', 'Kathua', 'Rajouri', 'Punch', 'Kupwara', 'Pulwama', 'Kulgam', 'Budgam', 'Ganderbal', 'Bandipora', 'Shopian', 'Reasi', 'Doda', 'Kishtwar', 'Ramban', 'Samba', 'Handwara', 'Uri', 'Tangmarg', 'Pahalgam', 'Gulmarg', 'Akhnoor', 'R S Pura', 'Vijaypur', 'Bishnah', 'Hiranagar', 'Marh'] },
  { state: 'Ladakh', cities: ['Leh', 'Kargil', 'Nubra', 'Diskit', 'Zanskar'] },
  { state: 'Lakshadweep', cities: ['Kavaratti', 'Agatti', 'Minicoy', 'Amini'] },
  { state: 'Puducherry', cities: ['Puducherry', 'Karaikal', 'Yanam', 'Mahe'] },
];

const STATES = LOCATIONS.map(s => s.state);

const CITIES_BY_STATE = Object.fromEntries(LOCATIONS.map(s => [s.state, s.cities]));

const ALL_CITIES = [...new Set(LOCATIONS.flatMap(s => s.cities))].sort();

// City -> state lookup, for deriving a legacy profile's state from its
// already-saved free-text city (first state wins on rare name collisions).
const STATE_OF_CITY = {};
LOCATIONS.forEach(s => {
  s.cities.forEach(c => {
    if (!(c in STATE_OF_CITY)) STATE_OF_CITY[c] = s.state;
  });
});

// A profile's chosen cities, normalized to an array regardless of whether it
// was saved on the new multi-select `cities` field or the legacy single
// `city` string — so every matching/filtering call site (discover, campaign
// audience, campaign relevance) only has to handle one shape. Returns []
// when the profile has set no location at all.
function profileCities(profile) {
  if (!profile) return [];
  if (Array.isArray(profile.cities) && profile.cities.length > 0) return profile.cities;
  if (profile.city) return [profile.city];
  return [];
}

module.exports = {
  LOCATIONS,
  STATES,
  CITIES_BY_STATE,
  ALL_CITIES,
  STATE_OF_CITY,
  profileCities,
};
